# config/meta.yml

meta_product_name: "Baromètre"
meta_title: "Baromètre - L'agenda des café-culture à Nantes"
meta_description: "Un agenda pour référencer tous les petits évènements théâtre et musique à Nantes"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
